[tox]
minversion = 4
envlist = lint,type,py3,docs
requires = tox-uv

[testenv]
usedevelop=True
setenv =
   PYTHONASYNCIODEBUG=1
extras = test
commands =
  coverage run -m pytest -s {posargs} -v -m "not realchroot"
  coverage report -m

[testenv:functional]
extras = test
commands =
  coverage run -m pytest -s {posargs} -v -m "realchroot"
  coverage report -m


[testenv:lint]
deps =
  flake8
  black
commands =
  flake8 {posargs}
  black --check --diff --line-length 120 chimg

[testenv:format]
extras = test
commands =
    black --line-length 120 chimg

[testenv:type]
extras = type
commands =
  mypy chimg

[testenv:docs]
extras = doc
commands =
  sphinx-build -M html docs docs-build

[flake8]
show-source = True
exclude = .venv,.tox,dist,doc,build,*.egg,node_modules
max-line-length = 120

[testenv:venv]
commands = {posargs}
