name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Run tox
        run: tox
  tox-functional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install tox and tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install mmdebstrap
        run: sudo apt install -y mmdebstrap
      - name: Run tox
        run: sudo $HOME/.local/bin/tox -efunctional
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: snapcore/action-build@v1
