name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.10", "3.12", "3.13"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          sudo apt install -y tox
      - uses: actions/checkout@v4
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox
  tox-functional:
    runs-on: ubuntu-latest
    steps:
      - name: Install tox and mmdebstrap
        run: |
          sudo apt install -y mmdebstrap tox
      - uses: actions/checkout@v4
      - name: Run tox
        # Run functional tests through tox
        run: sudo tox -efunctional
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
